### ISSUE TITLE
Wordcloud doesn't update properly

### ISSUE THREAD

**Issue by seiteta** [ToucanToco/changez-2017#1]
When using the wordcloud, some words should appear and disappear but they dont.

Example:

* If I select "Par tendance politique" then "Extreme Droite", then "Melenchon" should disappear
* If I select "Par tendance politique" then "Extreme Gauche", then "Le Pen" should disappear

(see the file https://github.com/ToucanToco/changez-2017/blob/master/question11-tendance.csv)

**Comment by davinov** [comment]
Thanks for noticing @seiteta !
Should be fixed by now
